config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#home"

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :tweets,        only: [:index, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  get    "signup"  => "users#new"
  get    "signin"  => "sessions#new"
  delete "signout" => "sessions#destroy"
  get    "about"   => "static_pages#about"

  match "*path" => "application#routing_error", via: :all
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @tweet = current_user.tweets.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def about
  end
end

app/views/static_pages/about.html.slim
h1 About
<<<<<<< HEAD
p Twitter clone app built with Ruby on Rails. See more details on <a href="https://github.com/batman1005">Github</a>.
p Author: <a href="https://mobile.twitter.com/echo_zym1005"> echo</a>
=======
p Twitter clone app built with Ruby on Rails. See more details on <a href="https://github.com/toshimaru/Rails-4-Twitter-Clone">Github</a>.
p Author: <a href="https://twitter.com/toshimaru_e"> toshimaru</a>
>>>>>>> 0cfef5180f68f1ce026b5b699349c66c6e33e0fe

app/views/static_pages/home.html.slim
.row
  - if signed_in?
    - provide(:title, 'Home')
    aside.col-md-4
      section
        = render 'shared/user_info'

    div.col-md-8
      .timeline
        h2.title Tweets
        = render 'shared/feed'

  - else
    - provide(:title, 'Welcome')
    div.col-md-12.one-col
      h1 Welcome to Twitter Clone
      p Start a conversation, explore your interests, and be in the know.

      = link_to 'Sign up', signup_path, class: "btn btn-primary"
      = link_to 'Sign in', signin_path, class: "btn btn-default"